Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Performing system checks...

Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/myfirstdjango/urls.py", line 27, in <module>
    path("polls/", include("polls.urls")),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/JABoo/miniconda3/envs/django/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/urls.py", line 2, in <module>
    from .views import index, index2, healthapp_intro, detail, results, vote, crazyfrog, calc
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/polls/views.py", line 11, in <module>
    import models.train_model as tm
  File "/Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src/django/myfirstdjango/models/train_model.py", line 6, in <module>
    import sklearn.model_selection as modsel
ModuleNotFoundError: No module named 'sklearn'
Watching for file changes with StatReloader
DEBUG:root:current directory : /Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src
[18/Jan/2023 15:34:14] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:35:38] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:09] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:10] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:13] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:15] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:16] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:16] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:16] "GET /polls/happ/ HTTP/1.1" 200 1628
[18/Jan/2023 15:36:16] "GET /polls/happ/ HTTP/1.1" 200 1628
Performing system checks...

System check identified no issues (0 silenced).
January 18, 2023 - 15:34:08
Django version 4.1.5, using settings 'myfirstdjango.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.










Watching for file changes with StatReloader
DEBUG:root:current directory : /Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src
[18/Jan/2023 15:48:21] "GET /polls/happ/ HTTP/1.1" 200 1628
Performing system checks...

System check identified no issues (0 silenced).
January 18, 2023 - 15:48:15
Django version 4.1.5, using settings 'myfirstdjango.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Performing system checks...

DEBUG:root:current directory : /Users/JABoo/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src
System check identified no issues (0 silenced).
January 19, 2023 - 09:01:45
Django version 4.1.5, using settings 'myfirstdjango.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.

[19/Jan/2023 09:01:50] "GET /polls/happ/ HTTP/1.1" 200 1628
Not Found: /polls/happs
WARNING:django.request:Not Found: /polls/happs
[19/Jan/2023 09:02:00] "GET /polls/happs HTTP/1.1" 404 3754

[19/Jan/2023 09:02:34] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:02:40] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:02:51] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:02:56] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:02:58] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:03:02] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:04:06] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:04:55] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:05:11] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:07:07] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:07:09] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:07:09] "GET /polls/happ/ HTTP/1.1" 200 1628

[19/Jan/2023 09:07:09] "GET /polls/happ/ HTTP/1.1" 200 1628
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
DEBUG:root:current directory : /media/psf/Home/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src
Performing system checks...

System check identified no issues (0 silenced).
January 19, 2023 - 10:14:08
Django version 4.1.5, using settings 'myfirstdjango.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
DEBUG:root:current directory : /media/psf/Home/workspace/hr/cursisten/cohort1/marc/MakeAIWork3-Marc/projects/healthapp/src
Performing system checks...

System check identified no issues (0 silenced).
January 19, 2023 - 10:14:26
Django version 4.1.5, using settings 'myfirstdjango.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
